# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RicBannerViewDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
 pod 'RicBannerView',:path => '..'
#pod 'RicBannerView'
pod 'SDWebImage'
  # Pods for RicBannerViewDemo

  target 'RicBannerViewDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RicBannerViewDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
